appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AJFYpOUJnEgqMR77KGPn3gGiWHzmKOPx+RpGbVvEcVvpSw3n2U3/kGZjP0MBGO5Dktq/wE/RuaeNrfCNwWGPp/EENmrunvPfMStEeaKlVGZWrTwajKjdCjKdHiLsEwigQgLesqTpiaiH1Sc2EKyjhH+36zzecqIz/eK8+6jekrOIS5meRbYzsZ3jOo9RHETiKeEW/2QBDssfS5mtUUGLpbMhKRvQ23LHG1p0zsFRWs2gtiTqkoeCE5kC2vXTud1VJ8l+6xxWf3TDnnTG+iBHt9/tEzdQBK4AuOCmph9GKfJ4Cp8cuTE8XJ42GEobeRaJ4Qd7tsCusvn8IEUVA+3ZJu8iTuDK6SQILW/1iQlxJdGFrvY/FTDef6OJHAW1tDRDfpHBlC6obKVVdkoV2DFuHK7GmZGrive+7FxxGkBMGtPE1SNRLons0mJ79NUpdcwyDC4AGbr4dyCe3rdWim4J+wPl/egMC6T1BbXyPYcqhgzSOYYIzbQ42U3yLa3GW28NNJJ4WZ6GAOB+2Mh4wN5TLS1gqk0SuI43ldeBSrv7OUWCrjAfjbb9vapWEwMbNI8sGS6n/aAF5IeyH7i1+qjUiuuGY0xkDHReBjRTQnGBH19+narCMLoOHc0f3XW6+KNCXimarwQqzhhE9PEUTbKhObE4u/gI8omGTYic8Y+NmBA=}
conda_forge_output_validation: true
