travis:
  secure:
    BINSTAR_TOKEN: Gx+FP7yYPWiOkM7w08wOelvcBhNl2+8IZIdWFDHw4LKOSkoDTSHW0sNFNkQtuDfNQ+CxtsRbxA3txdt4Ds/UXK7orMRjndtbDknqVLEt+M/EPFnJSTZxSt5e++ikaPZn99RA4O4Bh9kuAWyrkN6mv/mKypI7ydVHfi8NmOToVLax6B0vi6sJXU3UnkExd4wRwvjnnAAVQZcqyVnmG7rfieKKz4GInjIt+uGcsgJwMCxhMSveX/9t0G7ehPUQ38jhBSgg391emuvvwNuC0ddiTMKuAYM4qiBok6hZsf2qvI/AKHq7Q9Qr1PmbWn72UrBDfdGOwPR41hgY2GUdVv9p67DveAuTXh2tvLlGqSguc1uyrfeEKD4TR36N+W+PYmEAJUoBb4UZ2aW+OdbWpkhtfXDRvNB0lJdR/KroMXnioB5MwKJZtreyeSUXoVyDeLTg5hvFTFDyQExhxylSI5dPZgF2nyYuHYKcb3H4PY5VfD6lB7IOgXOWQuwIz5GITnQ3kgoo4FVJTQJfW8zdamy+aWNK7BQ27Vpq4Cy5al6l8wbr+B4i0QROa0aEhPJGjTjHkN+AfSBaDjYaIOFHtC9+FAsFGzxz9SummNncytnjOfhW46TH3T0rzeK4vJgKiue5zi0vwuWeL8dYiyvZGpnJRsiJmIwjzflUkr9/lrJOUCY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
